[package]
name = "loader-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "*"
egui_extras = { version = "*", features = ["all_loaders","image"] }
env_logger = { version = "*", features = ["auto-color","humantime"] }
log = "*"
